version: "3.8"
services:
  app:
    build: ./app
    volumes:
      - ./app:/app
    working_dir: /app/contests
    environment:
      - LOGIN_ID=${LOGIN_ID}
      - PASSWORD=${PASSWORD}
    entrypoint: /app/entrypoint.sh
    command: ["/bin/sh"]
    tty: true
